import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { CategoryProvider } from "@/context/CategoryContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-auto max-w-screen-lg">
          {/* I am doing this to test the context provider and fetch the category and change the category on click of the category button */}
          <CategoryProvider>
            <div className="flex min-h-screen flex-col items-center p-24">{children}</div>
          </CategoryProvider>
        </div>
      </body>
    </html>
  );
}
